/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElAddform: typeof import('element-plus/es')['ElAddform']
    ElAddformItem: typeof import('element-plus/es')['ElAddformItem']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    IEpArrowRight: typeof import('~icons/ep/arrow-right')['default']
    IEpGoods: typeof import('~icons/ep/goods')['default']
    IEpHandbag: typeof import('~icons/ep/handbag')['default']
    IEpIconMenu: typeof import('~icons/ep/icon-menu')['default']
    IEpLocation: typeof import('~icons/ep/location')['default']
    IEpMoney: typeof import('~icons/ep/money')['default']
    IEpPlus: typeof import('~icons/ep/plus')['default']
    IEpSearch: typeof import('~icons/ep/search')['default']
    IEpShoppingCart: typeof import('~icons/ep/shopping-cart')['default']
    IEpSwitchButton: typeof import('~icons/ep/switch-button')['default']
    IEpTickets: typeof import('~icons/ep/tickets')['default']
    IEpZoomIn: typeof import('~icons/ep/zoom-in')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
